[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "colorama>=0.4.6",
    "jinja2>=3.1.5",
    "mcstatus>=11.1.1",
    "requests>=2.32.3",
    "trafilatura>=2.0.0",
]
